asset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('', RedirectView.as_view(url='catalog', permanent=True)),

]

catalog/urls.py
from django.urls import path, re_path
from . import views
from .views import SearchResultsView, DeviceListView, DeviceDetailView, CustomerListView, CustomerDetailView

app_name = 'catalog'


urlpatterns = [
    path('index/', views.index, name='index1'),
    path('search/', SearchResultsView.as_view(), name='search_result'),
    # path('inventory/', InventoryListView.as_view(), name='inventory'),
    path('devices/', DeviceListView.as_view(), name='devices'),
    path('device/<int:pk>/', DeviceDetailView.as_view(), name='device-detail'),
    path('customers/', CustomerListView.as_view(), name='customers'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer_detail'),
    # path('trackers/', TrackerListView.as_view(), name='trackers'),
    # path('tracker/<int:pk>/', TrackerDetailView.as_view(), name='tracker_detail'),
    
]

catalog/models.py
from pickle import FROZENSET

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse

from .manufacturers import trusted_manufacturers

# Create your models here.


class Device(models.Model):
    """
    Model representing a devices (details).
    """
    serialn = models.CharField(max_length=100, null=False,  verbose_name="S/N", blank=True, help_text="Device's Serial Number")
    # datacenter = models.CharField(max_length=50, null=False,  verbose_name="DataCenter", default='sec-62 Noida', blank=False, help_text="Data Center")
    location = models.CharField(max_length=50, null=False,  verbose_name="Location", default='default rack', blank=False, help_text="Device Location")
    # location = models.ForeignKey('Location', null=False, help_text="Device Location", on_delete=models.PROTECT)
    datacenter_location = models.ForeignKey('Location', null=False, help_text="DataCenter Location", on_delete=models.PROTECT, default=1)
    # oem = models.ForeignKey('Manufacturer', null=False, verbose_name="OEM", help_text="Device Manufacturer", on_delete=models.PROTECT)
    oem = models.CharField(max_length=20, choices=trusted_manufacturers, blank=True, default='0',
                              help_text='Manufacturer', verbose_name="OEM")
    model = models.ForeignKey('Model', null=False, help_text="Device Model", on_delete=models.PROTECT)
    asset_type = models.ForeignKey('AssetType', null=False, help_text="Device Asset Type", on_delete=models.PROTECT)
    hostname = models.CharField(max_length=100, null=True, blank=False, verbose_name="Hostname")
    rack = models.CharField(max_length=50, null=True, blank=False, verbose_name="Rack")
    # lob = models.CharField(max_length=50, null=True, blank=False, verbose_name="LOB")
    lob = models.ForeignKey('LOB', on_delete=models.SET_NULL, null=True)
    ip = models.CharField(max_length=20, null=True, blank=False, verbose_name="IP Address")
    mgmt_ilo_ip = models.CharField(max_length=20, null=True, blank=False, verbose_name="Management ILO IP")
    assigned_spoc = models.ForeignKey('Customer', null=True, on_delete=models.SET_NULL)
    assigned_to = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True)
    managed_by = models.ForeignKey('Company', on_delete=models.SET_NULL, null=True)
    
    # Purchase related information
    po_number = models.CharField(max_length=50, null=True, blank=False, verbose_name="Purchase Number")
    po_date = models.DateField(null=True, blank=True, verbose_name="Purchase date")
    invoice_number = models.CharField(max_length=50, null=True, blank=False, verbose_name="Invoice Number")
    invoice_date = models.DateField(null=True, blank=True, verbose_name="Invoice date")
    mih_number = models.CharField(max_length=50, null=True, blank=False, verbose_name="MIH Number", help_text="Manfucturer Identification Number")
    project_name =  models.TextField(max_length=1000, null=True, blank=True, help_text="MIH Project Number")
    warranty_start_date = models.DateField(null=True, blank=False, verbose_name="Warranty Start Date")
    warranty_expiration_date = models.DateField(null=True, blank=True, verbose_name="Warranty End Date")
    amc_expiration_date = models.DateField(null=True, blank=True, verbose_name="AMC Expiration Date")
    tracking_number = models.CharField(max_length=50, null=True, blank=False, verbose_name="IR/MO  Number")
    
    # Statuses
    HW_STATUS = (
        ('0', 'Received'),
        ('1', 'Deployed'),
        ('2', 'Inactive'),
        ('3', 'In Stock'),
        ('4', 'Decommission'),
        ('5', 'Disposed'),
    )
    status = models.CharField(max_length=1, choices=HW_STATUS, blank=True, default='0',
                                 help_text='Asset Status', verbose_name="Asset Status")
    HW_SUBSTATUS = (
        ('0', 'Completed Shipment'),
        ('1', 'Functional'),
        ('2', 'Not In use'),
        ('3', 'In Inventory'),
        ('4', 'Decommissioned'),
        ('5', 'Disposed'),
    )

    substatus = models.CharField(max_length=1, choices=HW_SUBSTATUS, blank=True, default='0',
                                 help_text='Asset Sub Status', verbose_name="Asset Sub Status")
    eos = models.CharField(max_length=20, null=True, blank=False, verbose_name="EOS", help_text="End of Service")
    eol = models.CharField(max_length=20, null=True, blank=False, verbose_name="EOL", help_text="End of Life")
    support_status = models.CharField(max_length=20, null=True, blank=False, verbose_name="Support Status", help_text="Under warranty or AMC")

    # Audit fields
    # created = models.DateTimeField(auto_now_add=True, editable=True)
    # modified = models.DateTimeField(auto_now=True)
    notes = models.TextField(max_length=1000, null=True, blank=True, verbose_name="Remarks or Ticket Number", help_text="Enter a job description of the Device")

    def __str__(self):
        """
        String for representing the Model object.
        """
        if self.hostname:
            return self.hostname
        else:
            return self.serialn

    def display_customer(self):
        """
        Creates a string for the Customer. This is required to display model in Admin.
        """
        return ', '.join([model.name for model in self.model.all()[:3]])

    display_customer.short_description = 'Customer'

    def display_model(self):
        """
        Creates a string for the Model. This is required to display model in Admin.
        """
        return ', '.join([model.name for model in self.model.all()[:3]])

    display_model.short_description = 'Model'

    def status_verbose(self):
        return dict(Device.LOAN_STATUS)[self.status]

    def substatus_verbose(self):
        return dict(Device.LOAN_SUBSTATUS)[self.substatus]


    def get_absolute_url(self):
        """
        Returns the url to access a particular device.
        """
        return reverse('catalog:device-detail', args=[str(self.id)])

    # class Meta:
    #     ordering = ['-modified']
  

class AssetType(models.Model):
    """
    Model representing a devices type
    """

    assettype = models.CharField(max_length=200, help_text="Laptop / desktop etc")

    def __str__(self):

        return self.assettype


class Model(models.Model):
    """
    Model representing a devices model
    """
    name = models.CharField(max_length=200, help_text="Enter a hw Model")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name
    
class Customer(models.Model):
    """
    Model representing a Customer.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True)
    location = models.ForeignKey('Location', on_delete=models.SET_NULL, null=True)


    def get_absolute_url(self):
        """
        Returns the url to access a particular Customer.
        """
        return reverse('catalog:customer_detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Customer object.
        """
        return '%s, %s' % (self.last_name, self.first_name)

    class Meta:
        ordering = ['last_name']


class Location(models.Model):
    """
      Model representing set location/site for customer or device
    """

    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        """
        String for representing the Location object (in Admin site etc.)
        """
        return self.name

class Department(models.Model): 
    """
        Model representing set department for customer or Tracker
        # todo : Add : ESXI, Linux etc
    """
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        """
        String for representing the Department object (in Admin site etc.)
        """
        return self.name
    

class LOB(models.Model): 
    """
        Model representing set LOB for customer or Tracker
        # todo : Add : Telemedia, CloudOps etc
    """
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        """
        String for representing the LOB object (in Admin site etc.)
        """
        return self.name
    

# class Manufacturer(models.Model):
#     """
#         Model representing the manufacturers
#     """
#     name = models.CharField(max_length=50, blank=False, null=False)
#     description = models.CharField(max_length=50, blank=True, null=True)
#
#     class Meta:
#         ordering = ['id']
#
#     def __str__(self):
#         """
#         String for representing the Manufacturer object (in Admin site etc.)
#         """
#         return self.name
#
class Company(models.Model):
    """
        Model representing the Company. Eg Airtel, Accenture
    """
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        """
        String for representing the Company object (in Admin site etc.)
        """
        return self.name
    

catalog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.db.models import Count, Q
from .models import Device, Customer
from django.views import generic
from django.urls import reverse
import logging
from django.contrib import messages
from tablib import Dataset


# Create your views here.
def index(request):
    """
    Index page with count stock
    """
    #  "Count some devices
    num_devices=Device.objects.all().count()
    num_lt=Device.objects.filter(type__exact='3').count()
    num_dl_dep=Device.objects.filter(type__exact='3', status__exact='1').count()
    num_dv_new=Device.objects.filter(status__exact='0').count()
    num_dv_stk=Device.objects.filter(status__exact='3').count()
    num_dt = Device.objects.filter(type__exact='2').count()
    num_mt = Device.objects.filter(type__exact='9').count()

    num_authors=Customer.objects.count()
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # view HTML-template index.html with data
    # variable context
    return render(
        request,
        'index1.html',
        context={'num_devices':num_devices,
                 'num_authors':num_authors, 'num_visits':num_visits,
                 'num_lt':num_lt, 'num_dt':num_dt, 'num_mt':num_mt, 'num_dl_dep':num_dl_dep, 'num_dv_stk':num_dv_stk,
                 'num_dv_new':num_dv_new},
    )
    reverse('catalog_index1', args=())

""" Device List view """
class DeviceListView(generic.ListView):
    model = Device
    context_object_name = 'device_list'
    list_display = ('title', 'display_model', 'customer', 'display_status', 'serialn', 'substatus', 'tag')
    logging.debug("This is before device queryset")
    queryset = Device.objects.all()
    template_name = 'catalog/device_list.html'
    logging.debug("This is after device queryset")


    def get_queryset(self):
        return Device.objects.all()

""" Device detail view """
class DeviceDetailView(generic.DetailView):
    model = Device

    def device_detail_view(request, pk):
        try:
            device_id = Device.objects.get(pk=pk)
        except Device.DoesNotExist:
            raise Http404("Book does not exist")

        return render(
            request,
            'catalog/device_detail.html',
            context={'device': device_id, }
        )

""" Customer list view """
class CustomerListView(generic.ListView):
    model = Customer
    context_object_name = 'customer_list'   # ваше собственное имя переменной контекста в шаблоне
    list_display = ('last_name', 'first_name', 'department', 'location')
    queryset = Customer.objects.all()
    template_name = 'catalog/customer_list.html'
    paginate_by = 30

    def get_queryset(self):
        return Customer.objects.all()

""" Customer detail view """
class CustomerDetailView(generic.DetailView):
    model = Customer
    context_object_name = 'customer'

    template_name = 'catalog/customer_detail.html'

    def get_queryset(self):
        return Customer.objects.all()

    def get_context_data(self, **kwargs):
        cid = get_object_or_404(Customer, pk=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['customer_detail'] = Device.objects.filter(customer_id=cid)
        return context


# """ Tracker list view """
# class TrackerListView(generic.ListView):
#     model = Tracker
#     context_object_name = 'tracker_list'
#     template_name = 'catalog/tracker_list.html'
#     paginate_by = 30


# """ Tracker detail view """
# class TrackerDetailView(generic.DetailView):
#     model = Tracker
#     context_object_name = 'tracker'


#     template_name = 'catalog/tracker_detail.html'
#     def get_queryset(self):
#         return Tracker.objects.all()

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['tracker_listkz'] = Customer.objects.all()
#         return context

""" Search view """
class SearchResultsView(generic.ListView):
    model = Device
    template_name = 'search_result.html'


    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = Device.objects.filter(Q(title__icontains=query) | Q(status__icontains=query) |
                                            Q(serialn__icontains=query) | Q(customer__last_name__icontains=query) | Q(model__name__icontains=query))
        return object_list

# """ Inventory data view """
# class InventoryListView(generic.ListView):
#     model = Inventory
#     context_object_name = 'object_list'
#     template_name = 'inv.html'
#     paginate_by = 48

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Asset Management</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- CSS  -->

  {% load static %}
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</head>

<body>

  <div class="container">
{% block sidebar %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{% url 'catalog:index1' %}">AMC</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'catalog:index1' %}">Home (>O.o<)<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'catalog:devices' %}">Devices</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'catalog:customers' %}">Customer</a>
		</li>
		<li class="nav-item">
        <a class="nav-link" href="{% url 'catalog:inventory' %}">Inventory</a>
		</li>
          <li class="nav-item">
        <a class="nav-link" href="{% url 'catalog:trackers' %}">Tracker</a>
      </li>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Manage</a>
      </li>
    </ul>
    <form action="{% url 'catalog:search_result' %}" method="get" class="form-inline my-2 my-lg-0">
      <input  name="q" type="text" class="form-control mr-sm-2" placeholder="Search...">
    </form>
  </div>
</nav>
     {% endblock %}

    <div class="row">

      <div class="col-sm-12 ">
      {% block content %}

      {% endblock %}


          {% block pagination %}
  {% if is_paginated %}

          <nav aria-label="...">
  <ul class="pagination justify-content-center pagination-sm">
    <li class="page-item">
        {% if page_obj.has_previous %}
      <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
        {% endif %}
    </li>

    <li class="page-item active">
      <a class="page-link" href="#"> <span class="sr-only">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span></a>
    </li>

    <li class="page-item">
        {% if page_obj.has_next %}
      <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </li>
  </ul>
</nav>

  {% endif %}
{% endblock %}

      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/index1.html
{% extends "base_generic.html" %}

{% load static %}
{% block content %}
{% load bootstrap4 %}
<div class="container-fluid">
<h1>Asset Management</h1>

  <p>Welcome to <em>Asset Management</em>, a very basic Django website developed.</p>

<h2>Dynamic content :)</h2>

  <p>The base has the following record counts:</p>
  <ul>
    <li><strong>Devices:</strong> {{ num_devices }}</li>
    <li><strong>Laptops:</strong> {{ num_lt }}</li>
    <li><strong>Desktop:</strong> {{ num_dt }}</li>
	<li><strong>Monitor:</strong> {{ num_mt }}</li>
    <li><strong>Deployed:</strong> {{ num_dl_dep }}</li>
	  <li><strong>Stock:</strong> {{ num_dv_stk }}</li>
	  <li><strong>New:</strong> {{ num_dv_new }}</li>

    <li><strong>Customers:</strong> {{ num_authors }}</li>
  </ul>
<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
<table class="table table-striped table-hover table-bordered">
	<tbody>
		<tr>
			<td rowspan="2">Device</td>
			<th> Total </th>
			<td>Laptop</td>
			<td>Desktop</td>
			<td>Monitor</td>
		</tr>
		<tr>
			<th> {{ num_devices }}</th>
			<td>: {{ num_lt }}</td>
			<td>: {{ num_dt }}</td>
			<td>: {{ num_mt }}</td>
		</tr>
		<tr>
			<td rowspan="2">Inventory</td>
			<td>Deployed:</td>
			<td>Stock:</td>
			<td>New:</td>
		</tr>
		<tr>
			<td>{{ num_dl_dep }}</td>
			<td>{{ num_dv_stk }}</td>
			<td>{{ num_dv_new }}</td>
		</tr>
	</tbody>
</table>

</div>


{% endblock %}

catalog/templates/inv.html
{% load static %}
{% load qr_code %}
{% block content %}
<!-- list build by pages for print stickers -->
<style type="text/css">
body{

      font-family: Arial, Helvetica, sans-serif;
      margin-top: 78;
      margin-left: 36;
      margin-right 36;
    }
.grid {

      display: grid;
      grid-template-columns: repeat(4, 178px);
      grid-template-rows: repeat(12, 80px);
    }

.t {
   transform: rotate(90deg);
   transform-origin: top right;
   margin-left: 7rem;

}

    /* cell view */
    .grid > * {


      background-color: #ffbf94;
      border-radius: 5px;
      padding: 1px;
      margin: 4px;
    }
.page {
        width: 200px;
        height: 500px;
        background: #DD5555;
      }

      @page {
        size: A4;
        margin: 0;
      }


@media print {
    .more {
     page-break-after: auto;
    }
    .no-print {
    visibility: hidden;

  }
   }


  </style>


{% if object_list %}

    <div class="grid">
    {% for device in object_list %}
         <div>{% qr_from_text device.num size="T" %}
              {% qr_from_text device.snum size="T" %}
         <div class="t"><b>{{ device.snum }}<br>{{ device.num }}</b></div>
        <br>

         </div>
    {% endfor %}


    {% else %}
      <p>There are no data in the table.</p>
    {% endif %}
    </div>
<nav aria-label="...">
<div class="pagination justify-content-center pagination-sm no-print">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="page-item" href="?page=1">&laquo; first</a>
            <a class="page-item" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}

            <a class="page-item" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="page-item" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

    </span>
</div>
</nav>



{% endblock %}

catalog/templates/search_result.html
 {% extends "base_generic.html" %}

{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'dt/datatables.min.css' %}"/>

<script type="text/javascript" src="{% static 'dt/datatables.min.js' %}"></script>
    <h1>Search Results</h1>
	<p>filtering search result ------>>>>> </p>

 <table id="device" class="table table-striped table-hover table-responsive table-bordered">
    <thead>
      <tr>
          <td>Hostname</td>
          <td>Model</td>
          <td>Customer</td>
          <td>S/N</td>
          <td>Type</td>
          <td>Tag</td>
          <td>Status</td>

          </tr>
        </thead>
    <tbody>
      {% for device in object_list %}
          <tr><td><a href="{{ device.get_absolute_url }}">{{ device.title }}</a></td>
              <td>{{device.model}}</td>
              <td><a href="{{ device.customer.get_absolute_url }}">{{ device.customer }}</a></td>
              <td><a href="{{ device.get_absolute_url }}">{{device.serialn}}</a></td>
              <td>{{device.type}}</td>
              <td>{{device.tag}}</td>
              <td>{{device.status_verbose}}</td>
          </tr>

        </tbody>
   {% endfor %}
 </table>

<script>
    $(document).ready(function() {
    $('#device').DataTable( {
        "pagingType": "full_numbers",
        "lengthMenu": [[25, 40, 60, -1], [25, 40, 60, "All"]],
        "bProcessing":true
    } );
} );

</script>
<br>


{% endblock %}